namespace CWMII.lib.Enums {
	public enum Win32_PerfRawData_HvStats_HyperVHypervisorLogicalProcessor {
		Caption,
		Description,
		Name,
		Frequency_Object,
		Frequency_PerfTime,
		Frequency_Sys100NS,
		Timestamp_Object,
		Timestamp_PerfTime,
		Timestamp_Sys100NS,
		C1TransitionsPersec,
		C2TransitionsPersec,
		C3TransitionsPersec,
		ContextSwitchesPersec,
		Frequency,
		HardwareInterruptsPersec,
		HWPRequestMSRContextSwitchesPersec,
		HypervisorBranchPredictorFlushesPersec,
		HypervisorImmediateL1DataCacheFlushesPersec,
		HypervisorL1DataCacheFlushesPersec,
		HypervisorMicroarchitecturalBufferFlushesPersec,
		InterProcessorInterruptsPersec,
		InterProcessorInterruptsSentPersec,
		MonitorTransitionCost,
		ParkingStatus,
		PercentC1Time,
		PercentC1Time_Base,
		PercentC2Time,
		PercentC2Time_Base,
		PercentC3Time,
		PercentC3Time_Base,
		PercentGuestRunTime,
		PercentGuestRunTime_Base,
		PercentHypervisorRunTime,
		PercentHypervisorRunTime_Base,
		PercentIdleTime,
		PercentIdleTime_Base,
		PercentofMaxFrequency,
		PercentTotalRunTime,
		PercentTotalRunTime_Base,
		PerformanceMonitoringInterruptsPersec,
		PostedInterruptNotificationsPersec,
		ProcessorStateFlags,
		ReserveGroupId,
		RootVpIndex,
		RunningPriority,
		SchedulerInterruptsPersec,
		TimerInterruptsPersec,
		TotalInterruptsPersec
	}

	public static class Win32_PerfRawData_HvStats_HyperVHypervisorLogicalProcessorExtension {
		public static string GetWMIValue(this Win32_PerfRawData_HvStats_HyperVHypervisorLogicalProcessor enumOption) => lib.CWMII.GetSingleProperty($"SELECT * FROM Win32_PerfRawData_HvStats_HyperVHypervisorLogicalProcessor", enumOption.ToString());
	}
}