namespace CWMII.lib.Enums {
	public enum Win32_PerfFormattedData_PerfOS_Memory {
		Caption,
		Description,
		Name,
		Frequency_Object,
		Frequency_PerfTime,
		Frequency_Sys100NS,
		Timestamp_Object,
		Timestamp_PerfTime,
		Timestamp_Sys100NS,
		AvailableBytes,
		AvailableKBytes,
		AvailableMBytes,
		CacheBytes,
		CacheBytesPeak,
		CacheFaultsPersec,
		CommitLimit,
		CommittedBytes,
		DemandZeroFaultsPersec,
		FreeAndZeroPageListBytes,
		FreeSystemPageTableEntries,
		LongTermAverageStandbyCacheLifetimes,
		ModifiedPageListBytes,
		PageFaultsPersec,
		PageReadsPersec,
		PagesInputPersec,
		PagesOutputPersec,
		PagesPersec,
		PageWritesPersec,
		PercentCommittedBytesInUse,
		PoolNonpagedAllocs,
		PoolNonpagedBytes,
		PoolPagedAllocs,
		PoolPagedBytes,
		PoolPagedResidentBytes,
		StandbyCacheCoreBytes,
		StandbyCacheNormalPriorityBytes,
		StandbyCacheReserveBytes,
		SystemCacheResidentBytes,
		SystemCodeResidentBytes,
		SystemCodeTotalBytes,
		SystemDriverResidentBytes,
		SystemDriverTotalBytes,
		TransitionFaultsPersec,
		TransitionPagesRePurposedPersec,
		WriteCopiesPersec
	}

	public static class Win32_PerfFormattedData_PerfOS_MemoryExtension {
		public static string GetWMIValue(this Win32_PerfFormattedData_PerfOS_Memory enumOption) => lib.CWMII.GetSingleProperty($"SELECT * FROM Win32_PerfFormattedData_PerfOS_Memory", enumOption.ToString());
	}
}