namespace CWMII.lib.Enums {
	public enum Win32_PerfFormattedData_TCPIPCounters_TCPIPPerformanceDiagnostics {
		Caption,
		Description,
		Name,
		Frequency_Object,
		Frequency_PerfTime,
		Frequency_Sys100NS,
		Timestamp_Object,
		Timestamp_PerfTime,
		Timestamp_Sys100NS,
		Bytesoflostretransmitsretransmitted,
		Deniedconnectorsendrequestsinlowpowermode,
		IPv4NBLsindicatedwithlowresourceflag,
		IPv4NBLsindicatedwithoutprevalidation,
		IPv4NBLsPersecindicatedwithlowresourceflag,
		IPv4NBLsPersecindicatedwithoutprevalidation,
		IPv4NBLsPersectreatedasnonprevalidated,
		IPv4NBLstreatedasnonprevalidated,
		IPv4outboundNBLsnotprocessedviafastpath,
		IPv4outboundNBLsPersecnotprocessedviafastpath,
		IPv6NBLsindicatedwithlowresourceflag,
		IPv6NBLsindicatedwithoutprevalidation,
		IPv6NBLsPersecindicatedwithlowresourceflag,
		IPv6NBLsPersecindicatedwithoutprevalidation,
		IPv6NBLsPersectreatedasnonprevalidated,
		IPv6NBLstreatedasnonprevalidated,
		IPv6outboundNBLsnotprocessedviafastpath,
		IPv6outboundNBLsPersecnotprocessedviafastpath,
		RSCsegmentforwardingfailuresduringsoftwaresegmentation,
		RSCsegmentsforwardedviaLSO,
		RSCsegmentsforwardedviasoftwaresegmentation,
		RSCsegmentsforwardedviasoftwaresegmentationandchecksum,
		TCPchecksumerrors,
		TCPconnectrequestsfallenoffloopbackfastpath,
		TCPconnectrequestsPersecfallenoffloopbackfastpath,
		TCPinboundsegmentsnotprocessedviafastpath,
		TCPinboundsegmentsPersecnotprocessedviafastpath,
		TCPlossrecoveryepisodes,
		TCPRSCbytesreceived,
		TCPRSCevents,
		TCPsuccessfullossrecoveryepisodes,
		TCPtimeouts,
		UDPdatagramscreatedviasoftwaresegmentation,
		UDPURObytesreceived,
		UDPUROevents,
		UROsegmentationfailuresforrawsockets,
		UROsegmentationsforrawsockets,
		UROsegmentforwardingfailuresduringsoftwaresegmentation,
		UROsegmentsforwardedviasoftwaresegmentation,
		UROsegmentsforwardedviasoftwaresegmentationandchecksum
	}

	public static class Win32_PerfFormattedData_TCPIPCounters_TCPIPPerformanceDiagnosticsExtension {
		public static string GetWMIValue(this Win32_PerfFormattedData_TCPIPCounters_TCPIPPerformanceDiagnostics enumOption) => lib.CWMII.GetSingleProperty($"SELECT * FROM Win32_PerfFormattedData_TCPIPCounters_TCPIPPerformanceDiagnostics", enumOption.ToString());
	}
}