namespace CWMII.lib.Enums {
	public enum Win32_PerfFormattedData_PerfNet_Redirector {
		Caption,
		Description,
		Name,
		Frequency_Object,
		Frequency_PerfTime,
		Frequency_Sys100NS,
		Timestamp_Object,
		Timestamp_PerfTime,
		Timestamp_Sys100NS,
		BytesReceivedPersec,
		BytesTotalPersec,
		BytesTransmittedPersec,
		ConnectsCore,
		ConnectsLanManager20,
		ConnectsLanManager21,
		ConnectsWindowsNT,
		CurrentCommands,
		FileDataOperationsPersec,
		FileReadOperationsPersec,
		FileWriteOperationsPersec,
		NetworkErrorsPersec,
		PacketsPersec,
		PacketsReceivedPersec,
		PacketsTransmittedPersec,
		ReadBytesCachePersec,
		ReadBytesNetworkPersec,
		ReadBytesNonPagingPersec,
		ReadBytesPagingPersec,
		ReadOperationsRandomPersec,
		ReadPacketsPersec,
		ReadPacketsSmallPersec,
		ReadsDeniedPersec,
		ReadsLargePersec,
		ServerDisconnects,
		ServerReconnects,
		ServerSessions,
		ServerSessionsHung,
		WriteBytesCachePersec,
		WriteBytesNetworkPersec,
		WriteBytesNonPagingPersec,
		WriteBytesPagingPersec,
		WriteOperationsRandomPersec,
		WritePacketsPersec,
		WritePacketsSmallPersec,
		WritesDeniedPersec,
		WritesLargePersec
	}

	public static class Win32_PerfFormattedData_PerfNet_RedirectorExtension {
		public static string GetWMIValue(this Win32_PerfFormattedData_PerfNet_Redirector enumOption) => lib.CWMII.GetSingleProperty($"SELECT * FROM Win32_PerfFormattedData_PerfNet_Redirector", enumOption.ToString());
	}
}