namespace CWMII.lib.Enums {
	public enum Win32_PerfRawData_NvspSwitchStats_HyperVVirtualSwitch {
		Caption,
		Description,
		Name,
		Frequency_Object,
		Frequency_PerfTime,
		Frequency_Sys100NS,
		Timestamp_Object,
		Timestamp_PerfTime,
		Timestamp_Sys100NS,
		BroadcastPacketsReceivedPersec,
		BroadcastPacketsSentPersec,
		BytesPersec,
		BytesReceivedPersec,
		BytesSentPersec,
		DirectedPacketsReceivedPersec,
		DirectedPacketsSentPersec,
		DroppedPacketsIncomingPersec,
		DroppedPacketsOutgoingPersec,
		ExtensionsDroppedPacketsIncomingPersec,
		ExtensionsDroppedPacketsOutgoingPersec,
		LearnedMacAddresses,
		LearnedMacAddressesPersec,
		MulticastPacketsReceivedPersec,
		MulticastPacketsSentPersec,
		NumberofSendChannelMovesPersec,
		NumberofVMQMovesPersec,
		PacketsFlooded,
		PacketsFloodedPersec,
		PacketsPersec,
		PacketsReceivedPersec,
		PacketsSentPersec,
		PurgedMacAddresses,
		PurgedMacAddressesPersec,
		RSCCoalescedBytes,
		RSCCoalescedEventBucket10To1,
		RSCCoalescedEventBucket22To3,
		RSCCoalescedEventBucket34To7,
		RSCCoalescedEventBucket48To15,
		RSCCoalescedEventBucket516To31,
		RSCCoalescedEventBucket632To63,
		RSCCoalescedPacketBucket10To1,
		RSCCoalescedPacketBucket22To3,
		RSCCoalescedPacketBucket34To7,
		RSCCoalescedPacketBucket48To15,
		RSCCoalescedPacketBucket516To31,
		RSCCoalescedPacketBucket632To63,
		RSCCoalescedPackets,
		RSCCoalesceEvents,
		RSCPacketsProcessed
	}

	public static class Win32_PerfRawData_NvspSwitchStats_HyperVVirtualSwitchExtension {
		public static string GetWMIValue(this Win32_PerfRawData_NvspSwitchStats_HyperVVirtualSwitch enumOption) => lib.CWMII.GetSingleProperty($"SELECT * FROM Win32_PerfRawData_NvspSwitchStats_HyperVVirtualSwitch", enumOption.ToString());
	}
}