name: Build und Test und Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup sie .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore sie dependencies
      run: dotnet restore
    - name: Build sie package
      run: dotnet build CWMII.lib --configuration Release
    - name: Pack sie package
      run: dotnet pack --configuration Release CWMII.lib
    - name: Test sie Code
      run: dotnet test --no-build --verbosity normal
    - name: Publish sie package
      run: dotnet nuget push CWMII.lib/bin/Release/*.nupkg
